### PR TITLE
Signup-userpassform

### PR DESCRIPTION
**Pull request by ari-denary**
Example of how we might use Signup as the "smart" component, and conditionally render the appropriate form. 

Feel free to copy/paste/modify any doc examples you like, and add directly to the documentation within Signup so it shows all the hierarchy branches and routes in one place :)

Let me know any thoughts/questions/feedback you have!

### CODE REVIEW

**Review by joyceycodes — APPROVED** [review]
Awesome!!

**Comment by syangyue** [comment]
COOL!

**Comment by syangyue** [comment]
Amazing

**Review by syangyue — APPROVED** [review]
looks good

**Pull request merged**
